//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTZ.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DOTZ.Domain.Resources.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM Address
        ///WHERE CostumerId = @costumerId
        ///AND Description = @description.
        /// </summary>
        public static string Address_Get {
            get {
                return ResourceManager.GetString("Address.Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM Address
        ///WHERE CostumerId = @costumerId.
        /// </summary>
        public static string Address_GetAll {
            get {
                return ResourceManager.GetString("Address.GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM Address
        ///WHERE id = @id.
        /// </summary>
        public static string Address_GetById {
            get {
                return ResourceManager.GetString("Address.GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Address (CostumerId, Description, Street, number, Complement, PostalCode, Neighborhood, City, State)
        ///	VALUES (@costumerId, @description, @street, @number, @complement, @postalCode, @neighborhood, @city, @state).
        /// </summary>
        public static string Address_New {
            get {
                return ResourceManager.GetString("Address.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Address
        ///SET CostumerId = @costumerId
        ///   ,Description = @description
        ///   ,Street = @street
        ///   ,number = @number
        ///   ,Complement = @complement
        ///   ,PostalCode = @postalCode
        ///   ,Neighborhood = @neighborhood
        ///   ,City = @city
        ///   ,State = @state
        ///WHERE id = @id.
        /// </summary>
        public static string Address_Update {
            get {
                return ResourceManager.GetString("Address.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM Award
        ///WHERE CostumerId = @costumerId.
        /// </summary>
        public static string Award_GetAll {
            get {
                return ResourceManager.GetString("Award.GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Award (CostumerId, Description, Amount, DATE)
        ///	VALUES (@costumerId, @description, @amount, @date).
        /// </summary>
        public static string Award_Update {
            get {
                return ResourceManager.GetString("Award.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM Costumer
        ///WHERE UserId = @userId.
        /// </summary>
        public static string Costumer_Get {
            get {
                return ResourceManager.GetString("Costumer.Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	Balance
        ///FROM Costumer
        ///WHERE UserId = @userId.
        /// </summary>
        public static string Costumer_GetBalance {
            get {
                return ResourceManager.GetString("Costumer.GetBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Costumer (UserId, FirstName, LastName)
        ///	VALUES (@userId, @firstName, @lastName).
        /// </summary>
        public static string Costumer_New {
            get {
                return ResourceManager.GetString("Costumer.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Costumer
        ///SET FirstName = @firstName
        ///   ,LastName = @lastName
        ///WHERE UserId = @userId.
        /// </summary>
        public static string Costumer_Update {
            get {
                return ResourceManager.GetString("Costumer.Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Costumer
        ///SET Balance = @balance
        ///WHERE UserId = @userId.
        /// </summary>
        public static string Costumer_UpdateBalance {
            get {
                return ResourceManager.GetString("Costumer.UpdateBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	*
        ///FROM Orders
        ///WHERE CostumerId = @costumerId.
        /// </summary>
        public static string Order_GetByCostumer {
            get {
                return ResourceManager.GetString("Order.GetByCostumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Orders (CostumerId, ProductId, AddressId, OrderStatusId, Amount, DATE)
        ///	VALUES (@costumerId, @productId, @addressId, @orderStatusId, @amount, @date).
        /// </summary>
        public static string Order_New {
            get {
                return ResourceManager.GetString("Order.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Product WHERE Stock &gt; 0.
        /// </summary>
        public static string Product_GetAll {
            get {
                return ResourceManager.GetString("Product.GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	PRD.id
        ///   ,PRD.Name
        ///   ,PRD.Description
        ///   ,PRD.Amount
        ///   ,PRD.Stock
        ///   ,CT.Description AS Category
        ///FROM Product PRD
        ///INNER JOIN Category CT
        ///	ON CT.id = PRD.CategoryId
        ///WHERE PRD.Stock &gt; 0.
        /// </summary>
        public static string Product_GetAvailableWithCategory {
            get {
                return ResourceManager.GetString("Product.GetAvailableWithCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Product WHERE Id = @id.
        /// </summary>
        public static string Product_GetById {
            get {
                return ResourceManager.GetString("Product.GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Product (Name, Description, Amount, Stock, CategoryId) Values (@name, @description, @amount, @stock, @categoryId).
        /// </summary>
        public static string Product_NewProduct {
            get {
                return ResourceManager.GetString("Product.NewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Product SET Stock = @stock WHERE Id = @id.
        /// </summary>
        public static string Product_UpdateStock {
            get {
                return ResourceManager.GetString("Product.UpdateStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM UserAccounts WHERE Login = @login AND Pass = @pass.
        /// </summary>
        public static string User_Auth {
            get {
                return ResourceManager.GetString("User.Auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM UserAccounts WHERE Id = @userId.
        /// </summary>
        public static string User_GetById {
            get {
                return ResourceManager.GetString("User.GetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO UserAccounts (login, pass) VALUES(@login, @pass).
        /// </summary>
        public static string User_NewUser {
            get {
                return ResourceManager.GetString("User.NewUser", resourceCulture);
            }
        }
    }
}
